// app/src/components/activity/activity-list.tsx
"use client";

import { ActivityEntry, Role } from "@/lib/types";
import { usePagination } from "@/lib/use-pagination";
import { PaginationControls } from "@/components/ui/pagination-controls";
import { ActivityRow } from "./activity-row";
import { useCopy } from "@/lib/i18n/use-copy";

export function ActivityList({
  entries,
  role,
  ownerAccountId,
  loading = false,
}: {
  entries: ActivityEntry[];
  role: Role;
  ownerAccountId: string;
  // Owner view is on but its amounts have not arrived yet.
  loading?: boolean;
}) {
  const c = useCopy();
  const { paged, ...pagination } = usePagination(entries);

  if (entries.length === 0) {
    return <p className="px-5 py-8 text-center text-sm text-ink-500">{c.activity.emptyLabel}</p>;
  }

  return (
    <div>
      {paged.map((entry) => (
        <ActivityRow key={entry.id} entry={entry} role={role} ownerAccountId={ownerAccountId} loading={loading} />
      ))}
      {pagination.showControls && (
        <PaginationControls
          page={pagination.page}
          pageCount={pagination.pageCount}
          hasPrev={pagination.hasPrev}
          hasNext={pagination.hasNext}
          onPrev={pagination.prev}
          onNext={pagination.next}
        />
      )}
    </div>
  );
}

// console/src/lib/components/activity/ActivityList.svelte
<script lang="ts">
	import type { ActivityEntry, Role } from '$lib/types';
	import { Pagination } from '$lib/pagination.svelte';
	import PaginationControls from '$lib/components/ui/PaginationControls.svelte';
	import ActivityRow from './ActivityRow.svelte';
	import { getCopy } from '$lib/i18n';
	import { demo } from '$lib/store/demo-store.svelte';

	let {
		entries,
		role,
		ownerAccountId,
		// Owner view is on but its amounts have not arrived yet.
		loading = false
	}: { entries: ActivityEntry[]; role: Role; ownerAccountId: string; loading?: boolean } = $props();
	const c = $derived(getCopy(demo.language));
	const pagination = new Pagination(() => entries);
</script>

{#if entries.length === 0}
	<p class="px-5 py-8 text-center text-sm text-ink-500">{c.activity.emptyLabel}</p>
{:else}
	<div>
		{#each pagination.paged as entry (entry.id)}
			<ActivityRow {entry} {role} {ownerAccountId} {loading} />
		{/each}
		{#if pagination.showControls}
			<PaginationControls {pagination} />
		{/if}
	</div>
{/if}
