// app/src/components/ui/drawer.tsx
"use client";

import { X } from "lucide-react";
import { useEffect } from "react";
import { createPortal } from "react-dom";
import { useCopy } from "@/lib/i18n/use-copy";

export function Drawer({
  open,
  onClose,
  title,
  subtitle,
  children,
  footer,
}: {
  open: boolean;
  onClose: () => void;
  title: string;
  subtitle?: string;
  children: React.ReactNode;
  footer?: React.ReactNode;
}) {
  const c = useCopy();
  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [open, onClose]);

  if (!open) return null;
  if (typeof document === "undefined") return null;

  return createPortal(
    <div className="fixed inset-0 z-50 flex justify-end">
      <div
        className="absolute inset-0 bg-ink-900/30"
        onClick={onClose}
        aria-hidden="true"
      />
      <div
        role="dialog"
        aria-modal="true"
        aria-label={title}
        className="relative flex h-full w-full max-w-lg flex-col bg-surface shadow-2xl"
      >
        <div className="flex items-start justify-between gap-4 border-b border-border-subtle px-6 py-5">
          <div>
            <h2 className="text-base font-semibold text-ink-900">{title}</h2>
            {subtitle && <p className="mt-1 text-sm text-ink-500">{subtitle}</p>}
          </div>
          <button
            onClick={onClose}
            aria-label={c.common.close}
            className="rounded-lg p-1.5 text-ink-500 hover:bg-ink-900/5 focus-visible:outline focus-visible:outline-2 focus-visible:outline-brand-600"
          >
            <X size={18} />
          </button>
        </div>
        <div className="flex-1 overflow-y-auto px-6 py-5">{children}</div>
        {footer && (
          <div className="border-t border-border-subtle px-6 py-4">{footer}</div>
        )}
      </div>
    </div>,
    document.body
  );
}

// console/src/lib/components/ui/Drawer.svelte
<script lang="ts">
	import { X } from '@lucide/svelte';
	import type { Snippet } from 'svelte';
	import { getCopy } from '$lib/i18n';
	import { demo } from '$lib/store/demo-store.svelte';

	let {
		open,
		onClose,
		title,
		subtitle,
		children,
		footer
	}: { open: boolean; onClose: () => void; title: string; subtitle?: string; children: Snippet; footer?: Snippet } =
		$props();
	const c = $derived(getCopy(demo.language));

	function onKey(e: KeyboardEvent) {
		if (open && e.key === 'Escape') onClose();
	}
</script>

<svelte:window onkeydown={onKey} />

{#if open}
	<div class="fixed inset-0 z-50 flex justify-end">
		<div class="absolute inset-0 bg-ink-900/30" onclick={onClose} aria-hidden="true"></div>
		<div role="dialog" aria-modal="true" aria-label={title} class="relative flex h-full w-full max-w-lg flex-col bg-surface shadow-2xl">
			<div class="flex items-start justify-between gap-4 border-b border-border-subtle px-6 py-5">
				<div>
					<h2 class="text-base font-semibold text-ink-900">{title}</h2>
					{#if subtitle}<p class="mt-1 text-sm text-ink-500">{subtitle}</p>{/if}
				</div>
				<button
					type="button"
					onclick={onClose}
					aria-label={c.common.close}
					class="rounded-lg p-1.5 text-ink-500 hover:bg-ink-900/5 focus-visible:outline focus-visible:outline-2 focus-visible:outline-brand-600"
				>
					<X size={18} />
				</button>
			</div>
			<div class="flex-1 overflow-y-auto px-6 py-5">{@render children()}</div>
			{#if footer}
				<div class="border-t border-border-subtle px-6 py-4">{@render footer()}</div>
			{/if}
		</div>
	</div>
{/if}
